    ServerName web.internal
    ServerAlias 10.10.10.80

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/

    Header always set X-WAF-Status "ModSecurity Active"

    ErrorLog ${APACHE_LOG_DIR}/juiceshop_error.log
    CustomLog ${APACHE_LOG_DIR}/juiceshop_access.log combined

    <Location />
        SecRuleEngine DetectionOnly
    </Location>
</VirtualHost>
