
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy accept;
        iif lo accept
        ct state established,related accept
        tcp dport 22 accept
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
        iif ens37 ip saddr 10.10.10.0/24 accept
        log prefix "NFT-INPUT: " level warn
        accept
    }

    chain forward {
        type filter hook forward priority 0; policy accept;
        log prefix "NFT-FORWARD: " level info
        accept
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat;
        oif ens33 ip saddr 10.10.10.0/24 masquerade
    }
}
